### ISSUE TITLE
Header styling

### ISSUE THREAD

**Issue by Salakar** [invertase/docs.page#10]
More a nit picking than anything but GH H1s and H2s also add a horizontal line underneath which seems to break up the content a bit better:

docs.page:

![image](https://user-images.githubusercontent.com/5347038/102358484-75994780-3fa7-11eb-8292-8a7ce843d23b.png)

vs GH:

![image](https://user-images.githubusercontent.com/5347038/102358506-7d58ec00-3fa7-11eb-9e68-381178226a3f.png)

**Comment by Ehesp** [comment]
Can add a bottom border here: https://github.com/invertase/docs.page/blob/master/src/mdx/Heading.tsx#L41
