### ISSUE TITLE
incorrect active item in TOC sidebar menu & last item's content hidden

### ISSUE THREAD

**Issue by dylancom** [invertase/docs.page#110]
If I click on an item in the Table of Contents menu, it will "light up" 1 items before, until you scroll a little bit further.
It should be active directly after clicking on an item in the menu.

Example:
https://docs.page/invertase/react-native-google-ads
Click on for e.g. "Configure outbound requests" and the previous item "Setting up Google AdMob" will be highlighted instead.
<img width="757" alt="Schermafbeelding 2022-01-10 om 11 46 38" src="https://user-images.githubusercontent.com/12894112/148753554-5151a181-c92d-4341-8023-7f2adde91312.png">

**Comment by Ehesp** [comment]
Yeah the scroll-spy implementation isn't great now. It focuses on the ID which is tied to a heading vs the content. We're currently undergoing a rework of the rendering aspect and ui, and this is something we're going to sort by wrapping sections of content and using the intersection observer.

**Comment by Salakar** [comment]
We've just made v2 of `docs.page` live (lots of general improvements / styling & UI changes) - from what I can tell this seems to be behaving better now - please give it a try :)

**Comment by cabljac** [comment]
A little better - still not perfect but will look to improve this in future

**Comment by dylancom** [comment]
@Salakar hmm, not sure if this introduced another bug?
The last item, banner ads, are not shown at all: https://docs.page/invertase/react-native-google-mobile-ads/displaying-ads#banner-ads
While it does exist within the html...

**Comment by Ehesp** [comment]
Going to close this one. The item will only "light up" if the item has passed the top of the page. 

When clicking one on the page, it does correctly activate, however those at the bottom won't since the content never gets to the top. Not sure what to do about this really.
