### ISSUE TITLE
Tabs do not show content

### ISSUE THREAD

**Issue by JagandeepBrar** [invertase/docs.page#162]
For the custom components functionality you have shown it is possible to use tabs, however the tab content is not shown at all.

This can be replicated on the [components page itself](https://use.docs.page/components) in the docs.page documentation.

**Comment by cabljac** [comment]
Thanks! Looking into this now

**Comment by cabljac** [comment]
Found the issue, this should be fixed as part of https://github.com/invertase/docs.page/pull/163

**Comment by rydmike** [comment]
I noticed this issue too, I thought it was because I tried to show html tables as content, but seemed to be more general indeed. Looking forward to the fix.

**Comment by Salakar** [comment]
Fix is live, thanks

**Comment by JagandeepBrar** [comment]
Thanks! Can confirm that tabs are now working as expected 👍🏼
