### ISSUE TITLE
Feature not working: `navigation`

### ISSUE THREAD

**Issue by rydmike** [invertase/docs.page#170]
## `navigation` feature may be broken

I have tried to get the top `navigation` feature to work. So far I have failed. The sidebar works well, but not the top header navigation.

- Tried it together with sidebar, having `navigation` before and after in the `docs.json`config. No `navigation` appears.
- Tried it alone, no header `navigation` appears.

Thus in neither case can I get the header navigation to show. 

My use case for it was that I was trying to use a sidebar as my main nav of course, and to also put two links in the header navigation that would always be present there to two external places, just for convenience.

### Reproduction docs repo:

Here is a test reproduction repo: https://github.com/rydmike/docs_page_test
and site: https://docs.page/rydmike/docs_page_test

Having `docs.json` config file:
```json
{
    "name": "DocsPageTests",
    "favicon": "/images/favicon.png",
    "logo": "/images/logo.png",
    "logoDark": "/images/logo.png",
    "theme": "#0x29B6F6",
    "zoomImages": "true",
    "noindex": "false",
    "sidebar": [
        ["Welcome",
            [
                ["Intro","/"],
                ["More intro", "/more_intro"]
            ]
        ],
        ["Zoom image", "/another_page"]
    ],
    "navigation": [
        ["Intro","/"],
        ["More intro", "/more_intro"],
        ["Package", "https://pub.dev/packages/flex_color_scheme"],
        ["Playground", "https://rydmike.com/flexcolorscheme/themesplayground-v5"]
    ]
}
```

![image](https://user-images.githubusercontent.com/39990307/163253125-259217c3-f335-4f71-8dd0-914e32210661.png)

**Comment by cabljac** [comment]
I believe this is an error with the docs, and this is a feature we no longer support. I will double check.

**Comment by cabljac** [comment]
Yeah it seems like in an earlier version we had this, and no longer support it. We could add it back in potentially
