### ISSUE TITLE
bug: Different light and dark mode highlight "theme" color not respected

### ISSUE THREAD

**Issue by rydmike** [invertase/docs.page#175]
## Feature: Use different highlight "theme" color for light and dark mode.

Currently the same customizable color is used as highlight "theme" color for both light and dark mode. This is not ideal, since there are very few and limited color options that work well in both dark and light mode as a highlight "theme" color.

It would be useful if it was possible to specify separate custom colors for light and dark mode highlight color.

**Comment by Salakar** [comment]
Closing as this is supported now

**Comment by rydmike** [comment]
Awesome 👍 Going to make use of it soon. Thanks 🙏💙

**Comment by rydmike** [comment]
Does not seem to be working for me:

Config;
https://github.com/rydmike/flex_color_scheme_docs/blob/master/docs.json#L18-L24
Site result, still gets docs defaults:
https://rydmike.docs.page/flex_color_scheme_docs/all_themes

New issue? Or maybe I'm doing something wrong?

**Comment by Salakar** [comment]
Hmm that config seems correct - re-opening this issue

cc @Ehesp

**Comment by Ehesp** [comment]
@rydmike hey so this is because the config is in a sort of limbo where it's using new and old features, but the parser then assumes its the old style config. I've pushed a PR to fix this for you: https://github.com/rydmike/flex_color_scheme_docs/pull/3
