### ISSUE TITLE
Error on docs.page with Brave browser "TypeError: Cannot read properties of undefined (reading 'root')"

### ISSUE THREAD

**Issue by rydmike** [invertase/docs.page#179]
## Exotic minor issue when using Brave browser

If using Braving browser on Windows platform, if see this error when I open: https://docs.page/

```
TypeError: Cannot read properties of undefined (reading 'root')
    at ar (https://docs.page/_docs.page/_shared/chunk-CLNXGJXE.js:10:255)
    at Zi (https://docs.page/_docs.page/_shared/chunk-55NKYHF7.js:5:52842)
    at na (https://docs.page/_docs.page/_shared/chunk-55NKYHF7.js:9:8687)
    at qs (https://docs.page/_docs.page/_shared/chunk-55NKYHF7.js:9:933)
    at Qf (https://docs.page/_docs.page/_shared/chunk-55NKYHF7.js:9:864)
    at ut (https://docs.page/_docs.page/_shared/chunk-55NKYHF7.js:9:724)
    at yi (https://docs.page/_docs.page/_shared/chunk-55NKYHF7.js:7:10856)
    at Ve (https://docs.page/_docs.page/_shared/chunk-55NKYHF7.js:7:8416)
    at jr (https://docs.page/_docs.page/_shared/chunk-55NKYHF7.js:9:15760)
    at https://docs.page/_docs.page/_shared/chunk-55NKYHF7.js:9:17418
```` 
![image](https://user-images.githubusercontent.com/39990307/165376389-da9aac77-9d29-46dc-af8e-a5301e9a025a.png)

I see it also e.g. on these docs.page sites:

https://docs.page/invertase/melos
https://docs.page/rydmike/flex_color_scheme_docs/
https://docs.page/bizz84/complete-flutter-course/

This only with Brave browser, could not observe it with Chrome, Edge, Firefox.

It does not appear to show on Brave if I view the sites via their own domain, like these:

https://melos.invertase.dev/
https://docs.flexcolorscheme.com/

Then it is fine. I have been seeing this issue for couple of days, but I cannot really be sure when I saw it first time, but when I started using docs.page the issue did not exist with Brave browser. Possible of course that Brave has some new issue. Maybe their security thumb screws are too tight one or something.

Just thought I would let you guys know.

**Comment by cabljac** [comment]
Thanks. This looks like it could be something to do with the remix framework and routing. I saw this once a while ago and then couldn't reproduce.

**Comment by rydmike** [comment]
@cabljac just as info, I can no longer observe the above reported issue on any of the pages where I saw it with Brave browser before.

![image](https://user-images.githubusercontent.com/39990307/167314344-2fdb4419-2974-4bf9-a582-16ff6fee3230.png)

If you did not not do anything, maybe Brave did, since it was the only browser of quite few that I tried that had the issue, it is certainly a possibility, in case you did not fix something.
