### ISSUE TITLE
Error 500 on a new repo

### ISSUE THREAD

**Issue by koalik** [invertase/docs.page#184]
Just created a repo with npx @docs.page/init and cannot pass through 500 Internal Server Error:
https://docs.page/koalik/ecomet

**Comment by koalik** [comment]
Default template is incorrect - trailing comma is misplaced, producing invalid json. Once I removed it - all works.

**Comment by cabljac** [comment]
Sorry i think this needs to stay open until the bug is fixed, sounds like it's still an issue

**Comment by cabljac** [comment]
Hey I can't seem to reproduce this.

Are you running the cli via `npx` or `dart`?

**Comment by koalik** [comment]
Like that: "npx @docs.page/init". Just reproduced it again in another folder. Screenshot:

![2022-04-28 11_41-Clipboard](https://user-images.githubusercontent.com/104521534/165713587-e9f2990a-34c6-4fee-8047-d593a9fec36a.png)

**Comment by cabljac** [comment]
Thanks! will look into it and get it fixed asap

**Comment by cabljac** [comment]
Published a fix, thanks!
