### ISSUE TITLE
Sidebar nesting not working properly

### ISSUE THREAD

**Issue by JensHor** [invertase/docs.page#187]
I'm trying to create a sidebar that looks like the nested structure described in https://use.docs.page/configuration#sidebar:

```
{
  "sidebar": [
    ["Example", "/example"],
    [
      "Expandable",
      [
        ["Nested Example", "/example-nested"],
        ["Nested Expandable", [["Nested x2 Example", "/example-nested-x2"]]]
      ]
    ]
  ]
}
```

I'm expecting the sidebar to look this this
```
Example
Expandable
├─ Nested Example
├─ Nested Expandable
│  ├─ Nested x2 Example
```

But the sidebar actually is:
```
Example
Expandable
├─ Nested Example
```

Not only is `Nested x2 Example` missing but `Nested Expandable` is missing as well.

**Comment by cabljac** [comment]
Hi, thanks for raising this! Since v2 we support nesting to one depth only, as we found it was simpler to use and worked nicer with the sidebar. The docs need updating here.

If it's something you really need we could add support for more depth.

**Comment by JensHor** [comment]
Hi @cabljac, I understand that supporting only one layer of nesting makes sense from a UI and Design standpoint. Adding another layer would likely require some sort of redesign regarding the sidebar. 

For now, I do not require another layer of nesting because I can manage without it.

**Comment by cabljac** [comment]
@JensHor  Cool in that case i'll update the docs and close this :)
