### ISSUE TITLE
[feat] support any code block language

### ISSUE THREAD

**Issue by Ehesp** [invertase/docs.page#19]
Currently we require code languages manually, which won't work for all projects. Somehow we need to find a way to support dynamic languages.

https://highlightjs.org/ might be an option, however we'd have to ensure that the parsing of the language is carried out on the server (right now, it's on the client).

**Comment by Ehesp** [comment]
After some investigation, using highlight.js provides the following:

Pros:

- Any language supported (server side parsing)
- No client work required, simpler to manage

Cons:

- No support for line-numbers or line-highlighting

**Comment by Salakar** [comment]
Closes in #23
