### ISSUE TITLE
[Annoyance]: Embedded Tweets Animate to Target Width

### ISSUE THREAD

**Issue by rydmike** [invertase/docs.page#190]
## Embedded tweets animate SLOWLY to their set width

When using embedded tweets https://use.docs.page/components#tweet- and setting a size different to the default width, the embedded tweet animates from its default small width to desired width when the page is loaded or content is scrolled into view.

While this is kind of cute the first few times, it gets old pretty fast. It would be nice with a flag to turn this behavior off, or if simpler, not have any animation like this at all. It is not really needed or desired imo.

![docs-animate-tweet](https://user-images.githubusercontent.com/39990307/166108097-e2c55baa-3151-4df4-8810-1631e426f3ee.gif)

### Reproduction and repo:

Here is a test reproduction repo: https://github.com/rydmike/docs_page_test
and site: https://docs.page/rydmike/docs_page_test

Link to a page with embedded tweet that animates to its target width:
https://docs.page/rydmike/docs_page_test/more_intro

**Comment by cabljac** [comment]
that's annoying, didn't realize it did that, will remove. thanks!

**Comment by cabljac** [comment]
OK this is something to do with the 3rd party component i used. I'm just going to write our own so we can have control over it.

**Comment by rydmike** [comment]
Fix work great as can be seen here: https://docs.page/rydmike/docs_page_test/more_intro
Thanks!
