### ISSUE TITLE
[Issue]: Embedded Tweet Alignment No Impact - Always Centered 

### ISSUE THREAD

**Issue by rydmike** [invertase/docs.page#191]
# Alignment property on embedded tweets has no impact

When using embedded tweets https://use.docs.page/components#tweet- and setting `align` property, it has no impact, tweets always appear centered on rendered docs page. 

Example:

https://docs.page/rydmike/docs_page_test/tweet_align

Used mdx file: https://raw.githubusercontent.com/rydmike/docs_page_test/master/docs/tweet_align.mdx

## Reproduction repo

Here is a test reproduction repo: https://github.com/rydmike/docs_page_test
and site: https://docs.page/rydmike/docs_page_test

**Comment by cabljac** [comment]
should be fixed in https://github.com/invertase/docs.page/pull/194, feel free to reopen if still an issue

**Comment by rydmike** [comment]
Works great now as can be seen here: https://docs.page/rydmike/docs_page_test/tweet_align

Thanks!
