### ISSUE TITLE
[Feature]: Connect embedded tweet theme mode to effective site theme mode

### ISSUE THREAD

**Issue by rydmike** [invertase/docs.page#192]
# Embedded Tweet Theme Mode and Site Theme Mode Cannot Be Linked

The theme mode of embedded tweets can be set to light or dark mode, but this mode cannot be
linked to active/effective theme mode used by the user visiting the site.

**Proposal**: Provide an embedded theme mode for tweets that uses same theme mode for embedded tweets that the user is using on the site, regardless of if this setting is set to use light/dark/system, the mode of embedded tweets should match the effective result of site setting.

## Examples of not matched theme modes

https://docs.page/rydmike/docs_page_test/more_intro
![image](https://user-images.githubusercontent.com/39990307/166109513-decbf3c2-e4db-48dd-8086-8c3ba90b69d4.png)

https://docs.page/rydmike/docs_page_test/tweet_align
![image](https://user-images.githubusercontent.com/39990307/166109486-66d1a5f2-67ef-4585-92db-edcc32452f81.png)

## Reproduction repo

Here is a test reproduction repo: https://github.com/rydmike/docs_page_test
and site: https://docs.page/rydmike/docs_page_test

**Comment by cabljac** [comment]
fixed in https://github.com/invertase/docs.page/pull/194 :)

**Comment by rydmike** [comment]
@cabljac nice!
And it even updates when you toggle theme mode, wow! 
Test page: https://docs.page/rydmike/docs_page_test/tweet_align
Thanks!
