### ISSUE TITLE
Shields.io messes up tables

### ISSUE THREAD

**Issue by JensHor** [invertase/docs.page#195]
I'm using [shields.io](https://shields.io/) within a table, which somehow screws up the row alignment. 
I'm not totally sure if this is a bug or just a misconfiguration on my side, but i've never seen this problem on pub.dev, mdx preview or github.

**Code**

My markdown looks like this:

```
| Package           | Pub |
| ----------------- | --------------------------------- |
| [package:widgetbook_annotation](https://pub.dev/packages/widgetbook_annotation) | [![Pub Version](https://img.shields.io/pub/v/widgetbook_annotation?style=flat-square)](https://pub.dev/packages/widgetbook_annotation) |
```

**Expectation**
I'm expecting a rendered outcome that looks (kinda) like this:

| Package           | Pub |
| ----------------- | --------------------------------- |
| [package:widgetbook_annotation](https://pub.dev/packages/widgetbook_annotation) | [![Pub Version](https://img.shields.io/pub/v/widgetbook_annotation?style=flat-square)](https://pub.dev/packages/widgetbook_annotation) |

**What i am seeing:**

Somehow, the content of the left row is not aligned with the shields.io badge.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/16862002/166201204-7b3130f5-56f5-4110-a794-80dbbba948cf.png">

**Live view**

https://docs.widgetbook.io/~0adc7c3a8f5b28efdc084ec3742ab19d1f56348a/widgetbook-generator/setup

Let me know if additional info is required.
I appreciate your work and the amazing docs 👍🏻

**Comment by cabljac** [comment]
Thanks! Looking into this, it seems our prose styles are messing it up
