### ISSUE TITLE
feat: "categories" should be able to have content

### ISSUE THREAD

**Issue by Hunam6** [invertase/docs.page#204]
This config
```jsonc
"sidebar": [
	["index.mdx", "/"],
	["page-at-root.mdx", "/page-at-root"],
	[
		["part-one/index.mdx", "/part-one"], // this isn't allowed currently
		[
			["part-one/abc.mdx", "/part-one/abc"]
		]
	]
]
```
should make those pages available: `/`, `/page-at-root`, `/part-one` and `/part-one/abc`.

---

Right now the best equivalent is this
```jsonc
"sidebar": [
	["index.mdx", "/"],
	["page-at-root.mdx", "/page-at-root"],
	[
		"part-one",
		[
			["part-one/index.mdx", "/part-one"],
			["part-one/abc.mdx", "/part-one/abc"]
		]
	]
]
```

Which doesn't really work and even creates a bug when we click on "part-one/abc.mdx":

![Screenshot 2022-05-06 at 15 06 52](https://user-images.githubusercontent.com/38606542/167137322-3cf241a3-324a-4a88-8aea-cd31193c6f43.png)

**Comment by Ehesp** [comment]
Closing this one - we don't plan on supporting categories as a page at this time, sorry.
