### ISSUE TITLE
googleAnalytics config property not working?

### ISSUE THREAD

**Issue by JensHor** [invertase/docs.page#209]
I'm using the `googleAnalytics` property within the `docs.json` as used in e.g. [melos](https://github.com/invertase/melos/blob/main/docs.json). However, within [analytics.google.com](analytics.google.com) i'm not seeing any reported usage. 

Currently, I do not have anything deployed on my _main_ branch because I'm still setting the docs up. Therefore, my docs are currently only deployed as a PR. Is this a problem for the `googleAnalytics` property? 

In addition, I wasn't able to find any documentation regarding this property. Is there anything else that is required to get this working?

**Comment by cabljac** [comment]
Yeah seems like this is something we supported in v1, and was missed out in v2. I will add this back in :)

**Comment by JensHor** [comment]
Just checked out the PR. It seems to work. Can this issue be closed? 

Great job on enabling this 👍🏻

**Comment by cabljac** [comment]
Thanks! Only reason I didn't close was because i hadn't tested it yet.
