### ISSUE TITLE
zoom property of Image component causes image to be stretched

### ISSUE THREAD

**Issue by jenshor** [invertase/docs.page#210]
I'm using the `Image` component as documented in [Components - Image](https://use.docs.page/components#image-)

This is the code
`<Image src="/assets/Screenshot.jpg" zoom />`

When activating the image zoom, the image gets enlarged to the maximum canvas size of the browser. However, the zoom effect somehow distorts the image. In my case the fonts within the image look a bit off. 

Unzoomed:
<img width="2513" alt="image" src="https://user-images.githubusercontent.com/16862002/169521714-5a820715-2da4-49bd-aacf-72a0bdf5fbc0.png">

Zoomed:
<img width="2513" alt="image" src="https://user-images.githubusercontent.com/16862002/169521741-d6bdbadd-ed4a-414e-b329-a401b209b5fe.png">

For this example image it looks like the aspect ratio is different in the zoomed state. 

Let me know, if I can provide additional information. 

I love the zoom feature and would love to see it improved further 👍🏻

**Comment by cabljac** [comment]
Had a look into this today, we use `react-meium-image-zoom` to implement zooming, and im not sure the best way to fix this, I might have to refactor `Image` when i get a chance.

**Comment by JensHor** [comment]
Thanks @cabljac for looking into this. It's not something that is too much of an issue just something I noticed.

**Comment by cabljac** [comment]
Thanks for raising it! Appreciate it

**Comment by Ehesp** [comment]
I think this should be fixed now in the update. Please let me know if it still seems off to you.
