### ISSUE TITLE
An Empty docs.json file results in at 500

### ISSUE THREAD

**Issue by Thomascountz** [invertase/docs.page#213]
I hit a snag while creating a new project.

Particularly this step on the https://docs.page/ page:

> To get started, create an empty docs directory and a config docs.json file, both at the root of your repository.

I did the following:

```shell
$ touch docs.json
$ mkdir docs
$ echo "# Hello, World" > docs/index.mdx
$ git commit -am "init commit" && git push origin main
```

But when visited the docs.page site for my repo, I got a `500`.

This was because my `docs.json` file was empty.

Once I added an empty object to  `docs.json`, it worked as expected:

```json
{}
```

Perhaps this is because an empty `.json` file is not valid JSON?

**Comment by cabljac** [comment]
Thanks! will look into this

**Comment by cabljac** [comment]
This is a bug, it should use a default config in this situation.

**Comment by cabljac** [comment]
Yeah I can see why this is happening. I need to move the parsing and validating of configs to the api layer.
