### ISSUE TITLE
Indent subheadings in scroll-spy

### ISSUE THREAD

**Issue by loic-sharma** [invertase/docs.page#220]
Imagine I have a document with multiple levels of headings:

```
# Title
Hello

## Subheading
Some content

### Nested subheading
Wow

## Second Subheading
Much content
```

It'd be nice if the heading links in the "scroll spy", the right sidebar menu, are indented based off the subheading level:

```
Title
  Subheading
    Nested subheading
  Second Subheading
```

**Comment by blaugold** [comment]
I'd love to have this, specifically to better organize the [docs for the Melos configuration](https://melos.invertase.dev/configuration/overview#repository) to use heading levels that correspond to the nesting of the configuration item.

```markdown
<!-- Replace a heading like this -->
# ide/intellij/enabled

<!-- with the headings below. -->
# ide

## intellij

### enabled
```

Currently, our headings get so long that they don't fit into the TCO and get truncated.

**Comment by Salakar** [comment]
If someone would like to implemented this then I've added the hacktoberfest label so it will count towards [our Flutter hacktoberfest program](https://invertase.io/community/hacktoberfest).

**Comment by PriyanshuRj** [comment]
@Salakar can you please assign this issue to me.
