### ISSUE TITLE
Add PlausibleHQ functionality

### ISSUE THREAD

**Issue by cabljac** [invertase/docs.page#224]

**Comment by Salakar** [comment]
As requested by @Lyokone

**Comment by aggmoulik** [comment]
Hey @Salakar @cabljac , I would love to work on this issue. Do we have to implement plausible analytics on the documentation page?

**Comment by cabljac** [comment]
Hey @aggmoulik! That'd be awesome. Yeah i imagine would be similar to google analytics, where we add in a script, the user would provide any API key etc needed in their config file (docs.json) i think.

Let me know if you run into any issues getting the dev environment set up, and if you have any other questions :)

**Comment by aggmoulik** [comment]
I have only one question, how should I test my changes ?

**Comment by cabljac** [comment]
so that's the other big issue i wanted to put on hacktoberfest haha, i've been meaning to add comprehensive testing to the project for a while but not had a chance. In terms of testing this specific feature i'll have to think. Quite caught up on another project right now but hopefully can get back to you ASAP!
