### ISSUE TITLE
"Edit this page" link is incorrect for directory/index.mdx routes

### ISSUE THREAD

**Issue by cabljac** [invertase/docs.page#228]
This will probably require changing the API in order to provide whether it's an index.mdx page or not. Shouldn't need versioning as we can just add that as an extra field in the response

**Comment by PriyanshuRj** [comment]
I want to contribute to this issue can you explain more about it please as I am unable to get your exact point.

**Comment by Sanket2055** [comment]
can u please assign me this issue @cabljac !

**Comment by kumar-kalyan** [comment]
@cabljac can I work on it

**Comment by cabljac** [comment]
Hey guys sorry, removed the label - I figured out this is a one-liner, more of a bug. I fixed it in here https://github.com/invertase/docs.page/pull/238
