### ISSUE TITLE
Emails are removed by Cloudflare

### ISSUE THREAD

**Issue by bartekpacia** [invertase/docs.page#247]
[See example here](https://patrol.leancode.co/custom-finders/overview).

![Screenshot 2022-11-17 at 1 43 54 PM](https://user-images.githubusercontent.com/40357511/202449733-ec9d43fb-3d59-4683-b8ff-a66c06d0b12b.png)

Clicking on the [email protected] leads to a 404 page: https://patrol.leancode.co/cdn-cgi/l/email-protection

**Comment by Salakar** [comment]
Hey, sorry it took a while - this is now turned off on Cloudflare and I can see the emails coming through now

**Comment by bartekpacia** [comment]
Thanks! 💙
