### ISSUE TITLE
Longer titles are truncated instead of becoming multiline

### ISSUE THREAD

**Issue by bartekpacia** [invertase/docs.page#248]
[You can see behavior is on this site](https://patrol.leancode.co/tips-and-tricks).

I think the `h`s (`h1`, `h2`, etc.) should become multiline instead of truncating:

<img width="205" alt="Screenshot 2022-11-17 at 16 03 15" src="https://user-images.githubusercontent.com/40357511/202483285-6ccd7cf8-f474-4a19-aaf2-d9364652f4f3.png">

**Comment by cabljac** [comment]
This is in the sidebar?

**Comment by bartekpacia** [comment]
Yes.
