### ISSUE TITLE
Pages with code block are returning 500 

### ISSUE THREAD

**Issue by g-apparence** [invertase/docs.page#253]
Hi,
made some tests and it seems that all pages with some code  example are broke. 
See : https://docs.page/Apparence-io/camera_awesome/getting_started/custom-ui
Here's the content of the page: 
https://github.com/Apparence-io/camera_awesome/blob/master/docs/getting_started/custom-ui.mdx

To reproduce this add code like 
```dart
whatever you want
```

Page will now be in error

**Comment by apalala-dev** [comment]
While navigating on an other doc's repo, I also faced the error 500 but sometimes it works, not sure why.
This is the page that got me the error:
https://patrol.leancode.co/native/getting-started
After refreshing two times, it started working again.
After an other refresh, it's broken 😅

**Comment by Ehesp** [comment]
@Salakar @cabljac could this be the issue we saw posted on slack?

**Comment by Ehesp** [comment]
This should be sorted, however we're still investigating the root cause. Sorry about that
