### ISSUE TITLE
`gradle` syntax breaks preview

### ISSUE THREAD

**Issue by bartekpacia** [invertase/docs.page#255]
### Reproduction steps

1. Put this in some `.mdx` file:

    <pre>
    ```gradle
     buildscript {
       // ...
     }
     ```
     </pre>

2. Try to open that `.mdx` file using Local Preview feature. It should not work.

This is similar to #232 

I think some error reporting should be present. I understand that not all file formats are handled, but the current experience of Preview silently failing is really not intuitive.

**Comment by Ehesp** [comment]
Thanks will take a look - we're in the process of updating the internals and will put some form of error alert system in place.

**Comment by Ehesp** [comment]
Weirdly there is no syntax highlighting for gradle: https://github.com/shikijs/shiki/blob/main/docs/languages.md#all-languages

**Comment by Ehesp** [comment]
We'll have to figure out a nicer way to handle these error messages - bit tricky as they can arise from many places.

**Comment by bartekpacia** [comment]
> Weirdly there is no syntax highlighting for gradle: https://github.com/shikijs/shiki/blob/main/docs/languages.md#all-languages

I copy-pasted the `gradle` snippet from [integration_test's README](https://github.com/flutter/flutter/blob/master/packages/integration_test/README.md), and it's somewhat syntax-highlighted there.

**Comment by Salakar** [comment]
Gradle is `groovy` on Shiki, maybe we can alias gradle -> groovy
