### ISSUE TITLE
GitHub Bot doesn't work

### ISSUE THREAD

**Issue by bartekpacia** [invertase/docs.page#256]
I have set up [docs.page's GitHub app](https://github.com/apps/docs-page) on the [leancodepl/patrol](http://github.com/leancodepl/patrol) repository, but not once did I see a comment like this:

![comment](https://camo.githubusercontent.com/8cfbe71bea518fc61d6b443037de51f692a66f9e7f801227f1416e7a9cf1ab72/68747470733a2f2f7374617469632e696e766572746173652e696f2f6173736574732f646f63732e706167652f646f63732d706167652d626f742d6578616d706c652e6a7067)

**Comment by Ehesp** [comment]
Looking into this 👍

**Comment by nilsreichardt** [comment]
GitHub Bot is working for us again (see https://github.com/SharezoneApp/sharezone-app/pull/511#issuecomment-1470826692). Can be closed, right?
