### ISSUE TITLE
Preview doesn't work

### ISSUE THREAD

**Issue by bartekpacia** [invertase/docs.page#262]
https://docs.page/preview gives me 404.

**Comment by Ehesp** [comment]
The new API changes broke this, although the preview process should be much more straightforward now. Will sort tomorrow 👍

**Comment by BirjuVachhani** [comment]
I am seeing the same issue. This makes it much harder to work with!

**Comment by Ehesp** [comment]
Sorry about this - there's been an annoying issue which I didn't foresee in the rework (more on the UI side). I think I've found a workaround, however it'll take a bit longer than expected to get it working again.

**Comment by Abdulrasheed1729** [comment]
Still have the same issue, and the deployment page gives a 500 error page.

**Comment by BirjuVachhani** [comment]
This is a bummer! It been more than 4 months and no updates. It really hard to use docs.page without a local preview! Would highly appreciate if this gets fixed soon! 🤞🏻

**Comment by SaadArdati** [comment]
This is still broken. It makes MDX impossible to debug!

**Comment by chottuthejimmy** [comment]
Ya it's really hard to debug , I guess all we have to do is to create a pr and wait for the bot to assign the url

**Comment by BirjuVachhani** [comment]
Its been more than 6 months! Is this project abandoned?

**Comment by Ehesp** [comment]
Nope just never got around to it sorry - it's been sat on the backlog. Will try and get someone on it

**Comment by chottuthejimmy** [comment]
> Nope just never got around to it sorry - it's been sat on the backlog. Will try and get someone on it

Would really appreciate it :)

**Comment by mrverdant13** [comment]
Bump 👍🏼

**Comment by ImSingee** [comment]
Over one year...

**Comment by danisvaliev001** [comment]
@Ehesp are there any plans to fix it?

**Comment by Ehesp** [comment]
Yep @mhadaily is fixing this currently

**Comment by Welding-Torch** [comment]
Yes it does not work still.

**Comment by Ehesp** [comment]
https://github.com/invertase/docs.page/pull/340

**Comment by Salakar** [comment]
Preview is back! https://docs.page/preview

Sorry for the delay

**Comment by BirjuVachhani** [comment]
Still doesn't work for me! It is throwing this error to me!

```
Error loading /docs directory: DOMException: A requested file or directory could not be found at the time an operation was processed.
```

I am on M1 Mac with latest chrome browser.

**Comment by Ehesp** [comment]
Is this public anywhere for us to replicate?

**Comment by danisvaliev001** [comment]
> Is this public anywhere for us to replicate?

I have the same hardware (macbook air m1 2020), but have not any problem. Preview works nice in any browser, including latest chrome.

**Comment by BirjuVachhani** [comment]
@Ehesp This is my repo with docs folder in it!
https://github.com/hyper-designed/box_transform

You can try previewing it maybe?

Another of my struggle with this is that I can't select another directory to preview!

**Comment by mhadaily** [comment]
Just click on Restart and select a new folder 
<img width="1605" alt="Screenshot 2024-04-02 at 15 17 48" src="https://github.com/invertase/docs.page/assets/1325451/fde560b5-6410-4776-92da-bb361419aade">

I tested it, and it seems to work.

https://github.com/invertase/docs.page/assets/1325451/8866c257-4790-43f6-8404-4657bb4e3228

**Comment by BirjuVachhani** [comment]
I am not seeing any option to restart! This is what I am seeing! The `Select Directory` button is doing nothing. (It something for the first time when I selected a directory!)
<img width="1714" alt="image" src="https://github.com/invertase/docs.page/assets/20423471/66683f2c-42fa-4106-8809-7293639ea628">

**Comment by BirjuVachhani** [comment]
Ah! I am selecting wrong directory. I was selecting docs dir whereas I am supposed to select the parent of the docs directory. It worked now!

**Comment by mhadaily** [comment]
@BirjuVachhani Good. 

And Yes, we we are still improving this page.
