### ISSUE TITLE
Separete theme color for dark mode

### ISSUE THREAD

**Issue by bartekpacia** [invertase/docs.page#263]
I'd like to be able to set different theme color for light and dark mode. E.g my company has an accent color (bright yellow) that looks OK on black background, but on white background it's barely legible.

So I'm proposing introducing:

`themeDark`, in addition to `them` (there is already `logo` and `logoDark`)

**Comment by Salakar** [comment]
This seems reasonable, wdyt @Ehesp?

**Comment by Ehesp** [comment]
Started this here: https://github.com/invertase/docs.page/tree/feat/dark-theme

Need to properly try it out.

**Comment by bartekpacia** [comment]
Thanks so much! :)

Also while we're at it, it'd be nice to also add `faviconDark` (same case, my company's logo is black and white – https://patrol.leancode.co).

**Comment by Ehesp** [comment]
Light and Dark theme colours are now supported. Will create a separate issue for favicon.
