### ISSUE TITLE
Add diff code support

### ISSUE THREAD

**Issue by nank1ro** [invertase/docs.page#265]
Would be nice to have diff code support like this:
```diff
void main() {
-  print("before");
+  print("after");
}
```

**Comment by apalala-dev** [comment]
This would be helpful for migration guides.
From what I understood, GitHub markdown supports it but without being able to set both the language highlighting AND the diff highlighting.
Having both would be very nice 🔥

**Comment by Ehesp** [comment]
Hmm this should theoretically be supported already, since we use Shiki. Let me have a look.

**Comment by nank1ro** [comment]
> Hmm this should theoretically be supported already, since we use Shiki. Let me have a look.

Do you have any updates on this? Still not working on our end

**Comment by rodydavis** [comment]
working for me!

https://dartsignals.dev/flutter/watch/

![IMG_3821](https://github.com/invertase/docs.page/assets/31253215/3beeb2df-3a87-4097-85a9-121b76a53555)

**Comment by Ehesp** [comment]
This is now supported! https://invertase.docs.page/docs.page/components/code-blocks#diffing
