### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by bartekpacia** [invertase/docs.page#289]
See https://patrol.leancode.co/ci/firebase-test-lab for an example. Try to click on the `gcloud`-related links - they all print "service unavailable" when visited by clicking a link through `docs.page`-powered website.

But when I copy the URL and paste it in another browser window, they load just fine.

**Comment by Salakar** [comment]
I can't seem to replicate this 🤔 the links all work here

**Comment by bartekpacia** [comment]
Huh, works when I'm in incognito. 

I guess something's up with my Chrome.

Can't reproduce it reliably, so I'm closing this issue.
