### ISSUE TITLE
Toggling dark theme is a bit buggy

### ISSUE THREAD

**Issue by bartekpacia** [invertase/docs.page#291]
1. Toggle dark/light mode
2. Open a new page
3. The new page opens with the previously selected mode, not the currently selected

See the video:

https://user-images.githubusercontent.com/40357511/228220400-7d481a8b-7f54-43c6-9fa6-8777ad02fa0f.mov

**Comment by Ehesp** [comment]
This has now been fixed in the 2024 refresh
