### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by mjablecnik** [invertase/docs.page#298]
Hello. Do you support translation documentation into more languages like Docusaurus?:
![image](https://user-images.githubusercontent.com/2686906/229748459-d99ff7c5-c860-457a-9b79-98c8a706a7a9.png)

**Comment by Ehesp** [comment]
Have you seen https://use.docs.page/locales ?

**Comment by mjablecnik** [comment]
Hello, no I didn't see it. I didn't find it in your README features list:
![image](https://user-images.githubusercontent.com/2686906/229769271-127af5dd-c75e-425e-bc27-3cabd29cdf41.png)
so I thought that you don't support this feature.
