### ISSUE TITLE
`diff` syntax not working

### ISSUE THREAD

**Issue by bartekpacia** [invertase/docs.page#308]
Code:

```diff title="android/app/build.gradle"
 android {
   // ...
   defaultConfig {
     //...
-    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
+    testInstrumentationRunner "pl.leancode.patrol.PatrolJUnitRunner"
   }

+  testOptions {
+    execution "ANDROIDX_TEST_ORCHESTRATOR"
+  }
 }

 dependencies {
+  androidTestUtil "androidx.test:orchestrator:1.4.2"
 }
```

![Screenshot 2023-06-12 at 6 37 46 PM](https://github.com/invertase/docs.page/assets/40357511/30cd28a3-50ca-4f7f-a6c5-50264479c953)

Result:

![Screenshot 2023-06-12 at 6 38 03 PM](https://github.com/invertase/docs.page/assets/40357511/7b0a2f11-9f3b-4582-be53-73ad8eb4afe3)

**Comment by nank1ro** [comment]
duplicate of https://github.com/invertase/docs.page/issues/265

**Comment by bartekpacia** [comment]
Oh, sorry and thanks :)
