### ISSUE TITLE
Down 500 INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by andreabuttarelli** [invertase/docs.page#309]
Hi,
I cannot access any site that is on docs.page (including https://docs.page itself). Same error for all my colleagues.
Also trying sites with custom domains, the error is the same (https://docs.buildwiththeta.com).

Code: INTERNAL_FUNCTION_INVOCATION_FAILED

![IMG_0630](https://github.com/invertase/docs.page/assets/49411143/6f80670b-318c-4f3f-a3c9-9cae0490c21f)

**Comment by jordan-pieces** [comment]
Also can confirm the same issue here with docs at [docs.pieces.app](docs.pieces.app)

**Comment by Ehesp** [comment]
I believe this is due to the ongoing AWS incident happening at the moment.

Will double check

**Comment by jordan-pieces** [comment]
Thanks @Ehesp just wanted to make sure your team was aware just keep us posted! :)
