### ISSUE TITLE
Discord invite link is broken

### ISSUE THREAD

**Issue by sebastienvermeille** [invertase/docs.page#325]
Hey folks,

I could not join the discord the link is broken, could you update it please ?

Thank you

**Comment by sebastienvermeille** [comment]
Anyone here ?

**Comment by mhadaily** [comment]
Are you using https://invertase.link/discord, I have double-checked now and it works, it redirects me to Discrod page. Can you share your error?

**Comment by sebastienvermeille** [comment]
@mhadaily I talk about this link:

![docs page broken discord](https://github.com/invertase/docs.page/assets/4329594/90b10f06-7b10-4944-9fff-6597fd4246e8)

Which redirects to: `https://invertase.link/discord` and then to `https://discord.com/invite/C9aK28N` which is no longer a valid discord link.

**Comment by jordan-pieces** [comment]
@sebastienvermeille can we close this issue as it has already been handled from what I have seen. After just checking the link it seems to be working just fine 😄

**Comment by sebastienvermeille** [comment]
Hi @jwafu sure thx for updating the link :+1:
