### ISSUE TITLE
Docs Site Hosting Server Down?

### ISSUE THREAD

**Issue by jordan-pieces** [invertase/docs.page#335]
Currently I am unable to load the documentation site here where our docs are hosted at: http://docs.pieces.app

Also tested a few other sites on the domains.json just to ensure it was more than just a single domain: 
* https://docs.sedenion.net
* https://docs.yaroo.dev
* https://cleanframework.acmesoftware.com

These three also seem to be returning 500 server errors, along with the documentation site: https://use.docs.page/configuration as well. The https://docs.page landing page is loading for me though which is something to note.

**Comment by GregoryConrad** [comment]
One of my users reported the same thing with rearch.gsconrad.com yesterday or the day before, but after some hours it appeared to come up again. It is down now again though.

**Comment by Salakar** [comment]
Apologies all, our monitoring failed to pick this up. I restarted a bunch of services which seems to have resolved itself, I will do a full investigation on Monday and keep an eye on it for the rest of the weekend.

Same for the monitoring, will investigate on Monday

**Comment by jordan-pieces** [comment]
thanks @Salakar appreciate it! 😄

**Comment by mateuszwojtczak** [comment]
Hi @Salakar!
Unfortunately, it appears to be down again.

https://patrol.leancode.co/ returns ERR_CONNECTION_REFUSED :(

**Comment by jordan-pieces** [comment]
@Salakar  can confirm this has returned on our side as well for [https://docs.pieces.app](https://docs.pieces.app)

**Comment by Salakar** [comment]
Network issues with our custom domains proxy for docs.page - have fixed, should be up now.

Alerting picked it up so have fixed the issue (failover to new region + some routing rules tweaked).

After 4 years of no issues and then things go wrong all at once 😓 sorry again 🙈
