### ISSUE TITLE
Not load images in the assets folder because of CORB

### ISSUE THREAD

**Issue by innodep-joonk** [invertase/docs.page#356]
Thank you so much for open-sourcing your amazing project. I love how easy it is to use, but I'm having trouble using assets image.

Problem
: Not load images in the assets folder 

Console log
: Response was blocked by CORB (Cross-Origin Read Blocking)

How can I resolve it?

**Comment by Ehesp** [comment]
Do you have an example of this live I can investigate with?

**Comment by Ehesp** [comment]
Closing this one as no reproduction - please let me know if you are still having issues and I can reopen :)
