### ISSUE TITLE
Default tab should be `/` instead of `/{repo_name}`

### ISSUE THREAD

**Issue by yousinix** [invertase/docs.page#361]
Before the 2024 refresh (#359), the root _and only_ tab used to have the path `/` and not `/{repo_name}`. The trailing `/{repo_name}` makes the URL look a bit odd in case we only have a **single package**. Here's a comparison between the two routing schemes:

```
# Before 2024 refresh
https://widgetbook.docs.page/guides/quick-start

# After 2024 refresh (redundant /widgetbook)
https://widgetbook.docs.page/widgetbook/guides/quick-start
```

This change makes sense in the following cases, but not in ours.

1. Default domains
  
    ```
    https://docs.page/yousinix/lo_form/getting-started
    ```

2. Organization with multiple repos
  
    ```
    https://leancodepl.docs.page/patrol/getting-started
    https://leancodepl.docs.page/{some-other-package}/getting-started
    ```

**Comment by Ehesp** [comment]
Hey,

Yep this isn't ideal sorry - here's what happened:

We have custom domain support, in your case your docs pointed to docs.widgetbook.io. During our migration to the refresh we hit some issues upgrading our custom domain proxy which we didn't expect. We made the call to redirect custom domains to their vanity domain (`:org.docs.page/:repo`) as a temporary workaround whilst we upgrade the custom domain service. We didn't want to block the release on custom domains.

This is actively in progress, so we'll soon have docs.widgetbook.io back up and running.

**Comment by Ehesp** [comment]
Your specific issue is resolved. I've created a new issue to track custom domains: https://github.com/invertase/docs.page/issues/366
