### ISSUE TITLE
Selected tab is not highlighted for custom domains

### ISSUE THREAD

**Issue by yousinix** [invertase/docs.page#362]
The selected tab is no longer highlighted in the sidebar for custom domains:

#### [Custom Domain](https://invertase.docs.page/docs.page/navigation)

![Custom Domain](https://github.com/user-attachments/assets/38b98e08-69df-4631-a75e-ee9f3109b93b)

#### [Default Domain](https://docs.page/yousinix/lo_form/getting-started)

![Default Domain](https://github.com/user-attachments/assets/ded3fee5-367e-42bc-a9d6-d1172f34bf8d)

**Comment by Salakar** [comment]
Thanks! This has been fixed now
