### ISSUE TITLE
bug: Page with TS codeblocks causes Internal Server Error

### ISSUE THREAD

**Issue by DoctorJohn** [invertase/docs.page#364]
Starting a few days a go one of the react-native-google-mobile-ads pages started showing the following error message:

<details>

![image](https://github.com/user-attachments/assets/ad7b15cb-178f-49ab-9dcc-3b20c869fcf4)

</details>

The page used to work flawlessly before, so I assume this has something to do with #359. Checking the browsers dev tools reveals that the `GET` request to `https://docs.page/invertase/react-native-google-mobile-ads/impression-level-ad-revenue` results in an internal server error (status 500).

I narrowed the problem down to the following two codeblocks in our docs:

https://github.com/invertase/react-native-google-mobile-ads/blob/b4443b473bba2322b8b7f0b80ed9cd7689af8f0a/docs/impression-level-ad-revenue.mdx?plain=1#L26-L39

Removing them OR(!) switching their language from `ts` to `tsx` resolved the problem, which can be verified by looking at the [preview of the branch I used for debugging](https://docs.page/DoctorJohn/react-native-google-ads~fix-docs-page/impression-level-ad-revenue).

**Comment by Ehesp** [comment]
@DoctorJohn Thanks for reporting. This was because of the twoslash rendering which has now been removed. Unfortunately it can't handle external types without them being explicitly installed which won't work for docs.page. 

The page is live again.
