### ISSUE TITLE
Navigation of PR previews not working

### ISSUE THREAD

**Issue by yousinix** [invertase/docs.page#380]
The link that is posted on a PR is just working for the index page, if you try to navigate to any other page, a leading slash before the PR number breaks it all (~XXX)

### Steps to reproduce:

1. Go to `https://widgetbook.docs.page/widgetbook~1275` (from [this comment](https://github.com/widgetbook/widgetbook/pull/1275#issuecomment-2383030945)).
1. Try to navigate to any page.
1. Notice the slash in the URL:

    ```
    # Expected
    https://widgetbook.docs.page/widgetbook~1275/guides/quick-start
    
    # Actual (has slash between widgetbook and PR number)
    https://widgetbook.docs.page/widgetbook/~1275/guides/quick-start
    ```

**Comment by Ehesp** [comment]
This is fixed - custom domains are working again and there was some URL building logic which needed modifying to correct this scenario. Thanks for flagging!
