### ISSUE TITLE
Anchors no longer show up on top of side menu

### ISSUE THREAD

**Issue by rydmike** [invertase/docs.page#384]
[Anchors](https://use.docs.page/configuration#anchors) used to show up at the top of the side menu, after recent updates they seem to be gone:

![Screenshot 2024-10-06 at 17 13 38](https://github.com/user-attachments/assets/1823e13f-6b05-4f0d-a332-00fd127e51ac)

Example usage on https://docs.flexcolorscheme.com/installing and its config https://github.com/rydmike/flex_color_scheme_docs/blob/master/docs.json

**Comment by Ehesp** [comment]
Ah, "link" should now be "href" to keep consistent with the rest:

https://use.docs.page/configuration#anchors

**Comment by rydmike** [comment]
Eh and lol, thanks yes that works 😄 

Maybe when you break the `docs.json` config API, consider adding big red info/warning text about it to the docs?

What I experienced now was that the past Anchors feature just appeared to be "gone" without any info anywher. I mean, sure I checked docs, to see that yup `Anchors` are still there with a title, icons and url. I would never have noticed that you changed "link" syntax to "href".

Sure it was not consistent with the other links, but this is the kind of thing that once you configured it and it works, you don't really bother looking at details like this again. Unless there is a really big warning about it in the doce when you look for explanations on why it is no longer working.

Anyway, thanks for the info, this works. Closing the issue.

**Comment by Ehesp** [comment]
Yep that was my bad - the idea was to automatically migrate old schemas to the new ones, which does work - this just fell apart when people mixed them.

**Comment by bizz84** [comment]
Just landed here. When was the syntax changed?

@Ehesp not sure if this is only about anchors. Sites such as the old GoRouter documentation are now broken and the sidebar is missing entirely: https://docs.page/csells/go_router

Example of old syntax: https://github.com/csells/go_router/blob/main/docs.json
