### ISSUE TITLE
Linked Sidebar Group Usability

### ISSUE THREAD

**Issue by pvande** [invertase/docs.page#399]
Given a config file that contains the following:

```json
{
  //...
  "sidebar": [
    {
      "title": "Basics",
      "href": "/"
    },
    {
      "group": "Advanced",
      "href": "/advanced",
      "pages": [
        {
          "title": "Customization",
          "href": "/advanced/customization"
        }
      ]
    }
  ],
  //...
}
```

The links to "Basics" and "Customization" behave exactly as expected, and to my delight, the "Advanced" group heading also linked to the page indicated as well! That said, attempts to open or close the group _without_ following the link were frustrating — the entirety of the list item is linked, except the caret, which does nothing when clicked.

I suspect that my behavioral expectations for this case are that clicking in the "void space" of the list item, or directly on the caret itself, would toggle the visibility of the group, and that only the _text_ of the entry would actually cause a page navigation.

---

On a related note, if the "Advanced" group is expanded when I click on the entry, I end up at `/advanced`, but the group will be closed. While I can see the argument for this behavior, it seems a bit odd to have begun navigating deeper into this tree only to have the (previously visible!) way shut in front of you.

**Comment by Ehesp** [comment]
Thanks for this feedback, very useful. The carat not clicking is a bug for sure, and I agree that if advanced is navigated to it should persist open. These are considered bugs which I'll investigate 👍

**Comment by Ehesp** [comment]
Just pushed up a fix for this - let me know if this meets what you think feels right?

**Comment by pvande** [comment]
Seems better. Thanks for the quick turnaround!
