### ISSUE TITLE
Image height/width attributes currently ignored

### ISSUE THREAD

**Issue by Salakar** [invertase/docs.page#6]
Images on the markdown on this page specify a `height` attribute which GH markdown parses successfully as seen on the right, docs.page strips it out as seen on left

![image](https://user-images.githubusercontent.com/5347038/102355184-6ca67700-3fa3-11eb-951b-c9d29139c6d9.png)

**Comment by Ehesp** [comment]
Might need to check the properties here: https://github.com/invertase/docs.page/blob/master/remark-sanitize-jsx.js#L18

The properties **should** be passed down to the JSX from there.
