### ISSUE TITLE
docs.page not reachable `TOO_MANY_FORKS`

### ISSUE THREAD

**Issue by leisim** [invertase/docs.page#64]
I'm seeing the following error when trying to open docs.page

<img width="577" alt="issue" src="https://user-images.githubusercontent.com/13610195/142719946-ea5b08fa-b8af-4e0f-899d-11b9088e952b.png">

**Comment by andgar2010** [comment]
also same

**Comment by Ehesp** [comment]
We've got an open ticket with Vercel open, literally no idea why this is happening. We've tried rolling back releases, deleting everything from the homepage but nothing works. 

Docs sites are working still, just weirdly the homepage does not

**Comment by cabljac** [comment]
Made some progress on debugging this today, appears it might be something to do with our rewrites for custom domains.

**Note for any users of docs.page reading this:** you can still reach the documentation of docs.page itself at https://use.docs.page/

**Comment by peteralbert** [comment]
FYI: We're facing the same issue with Vercel - for us it is the number of entries in the vercel.json redirects config. If we have 11 it works, once we add a 12th, we get this error. Ticket with Vercel is open...

**Comment by cabljac** [comment]
> FYI: We're facing the same issue with Vercel - for us it is the number of entries in the vercel.json rewrites config. If we have 11 it works, once we add a 12th, we get this error. Ticket with Vercel is open...

I have a workaround where i actually added a redirect for our homepage to the route /homepage

...not ideal but better than the error message. Hope this helps

**Comment by Salakar** [comment]
Moving away from vercel so closing this issue.
