### ISSUE TITLE
Content width/padding styling

### ISSUE THREAD

**Issue by Salakar** [invertase/docs.page#8]
Comparing the content width to GH markdown it's a lot thinner in width (GH to me feels a lot easier to read) :

![image](https://user-images.githubusercontent.com/5347038/102355907-69f85180-3fa4-11eb-8d71-7379dbadcbc1.png)

----

Changing the article classes attribute to `prose dark:prose-dark px-6 lg:px-6 py-6 desktop:py-20 mx-auto max-w-5xl` improves this quite a bit:

![image](https://user-images.githubusercontent.com/5347038/102356478-28b47180-3fa5-11eb-9df4-64ac26e61213.png)

----

Note the additional px padding change too added above to the classes attribute edit which improves mobile:

**Before padding change:**
![image](https://user-images.githubusercontent.com/5347038/102356665-69ac8600-3fa5-11eb-98b7-9b4f967feaf1.png)

**After padding change:**

![image](https://user-images.githubusercontent.com/5347038/102356554-42ee4f80-3fa5-11eb-9de1-5d4e2c85830a.png)

**Comment by Ehesp** [comment]
This is what the Tailwind prose plugin suggests - can override it, I don't really have a preference as long as it's not too wide.
