### ISSUE TITLE
Local preview mode not working (Chrome)

### ISSUE THREAD

**Issue by dylancom** [invertase/docs.page#99]
Local preview mode doesn't seem to be working in Chrome.
After selecting the directory, then accepting the permissions, nothing happens.

**Comment by cabljac** [comment]
Hi, 

Are you selecting the directory that contains the docs subdirectory (the root of the whole project)?

**Comment by dylancom** [comment]
Oops, was selecting the docs folder. 🙃

**Comment by cabljac** [comment]
I'm going to make this more clear haha, don't worry you're not the first :D

**Comment by dylancom** [comment]
Haha, anyway amazing feature / package!

**Comment by cabljac** [comment]
Thanks!
